version: "3.5"

services:
  redis:
    image: redis
    container_name: redis

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - "redis"
